services:
  db:
    image: mysql:5.7 
    hostname: db
    container_name: db
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
      - bak:/var/lib/mysql-files
    networks:
      - default-network
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: mysqldev
      MYSQL_PASSWORD: mysqldevpassword1!
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      # MYSQL_ROOT_PASSWORD: SuperSecretPassword123!

  adminer:
    image: adminer:latest
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - default-network
    depends_on:
      - db
    expose:
      - 8080

volumes:
  data:
  bak:

networks:
  default-network:
    external: true